### ISSUE TITLE
Why not report AUC score in the paper. 

### ISSUE THREAD

**Issue by chiyuzhang94** [Veason-silverbullet/UniTRec#1]
Hi @Veason-silverbullet .

Thanks for the great work. 
I have a quick question about your paper. I wonder why you do not include AUC as one of the metrics in your paper. Because AUC is a commonly used metric for these datasets. Is there any trouble to get AUC from your model?

Best,
Chiyu

**Comment by Veason-silverbullet** [comment]
Hi @chiyuzhang94 .

It is because for the task `QuoteRec`, there is only one ground-truth candidate. Applying AUC is less meaningful for single ground-truth, as it would get very high numeric results (i.e., 90+, as I remember) and make it hard to compare recommendation performance.

To calculate AUC for `NewsRec` and others, I recommend this code [https://github.com/Veason-silverbullet/DIGAT/blob/master/evaluate.py](https://github.com/Veason-silverbullet/DIGAT/blob/master/evaluate.py). 

Thanks for your in-depth question.

**Comment by chiyuzhang94** [comment]
Thanks for your answer.
